apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 8.5.1
    helm:
      valueFiles:
        - values/kibana-values.yaml
  sources:
    - repoURL: https://github.com/akansh23-cloud/k8s-gitops-platform.git
      targetRevision: master
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

