apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 8.5.1
    helm:
      values: |
        replicas: 1

        # IMPORTANT: your Elasticsearch is secured (401 without creds),
        # so use https
        elasticsearchHosts: "https://elasticsearch-master:9200"

        # Secrets created by elasticsearch chart
        elasticsearchCredentialSecret: elasticsearch-master-credentials
        elasticsearchCertificateSecret: elasticsearch-master-certs
        elasticsearchCertificateAuthoritiesFile: ca.crt

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Disable the pre-install job (it keeps failing/looping in your cluster)
        preInstall:
          enabled: false

        extraEnvs:
          - name: ELASTICSEARCH_REQUESTTIMEOUT
            value: "120000"
          - name: ELASTICSEARCH_PINGTIMEOUT
            value: "120000"
          - name: ELASTICSEARCH_SHARDTIMEOUT
            value: "120000"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
