apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 8.5.1
    helm:
      values: |
        replicas: 1

        elasticsearchHosts: "http://elasticsearch-master:9200"

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        extraEnvs:
          - name: ELASTICSEARCH_REQUESTTIMEOUT
            value: "120000"
          - name: ELASTICSEARCH_PINGTIMEOUT
            value: "120000"
          - name: ELASTICSEARCH_SHARDTIMEOUT
            value: "120000"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
